### ISSUE TITLE
confusing how to use

### ISSUE THREAD

**Issue by Fiiti** [Icinga/icinga-php-library#4]
Gentlemen,
when trying to install the director, you are first told to have ipl as a prerequisite.
If you click on it, you end up on the icingaweb2-module-ipl git page. It says "DEPRECATED" in big letters and links you here.

If you now read.me, it talks about v1.0.0 Stable "Checking out a branch like stable/1.0.0 or a tag like v1.0.0 is fine."

Now there seems to be nowhere - but a reference to a nightly 0.6, which is suitable for production in an another issue.

What must be copied or installed now please exactly where and how? Must make still be used?
I am puzzled, such a large software, like the director, with such a heavy start is provided.
I hope not to have overlooked anything.
Thanks in advance for any understandable guidance or advice.

Regards Fii

**Comment by nilmerg** [comment]
We are currently in the process of switching from the *module* IPL to the *library* IPL.

The Director depends on the module. And although the module is *deprecated*, this does not mean it's not usable anymore. It just means it's not getting updates anymore.

Since the Director depends on the 0.3.0 version of the module, which isn't even the latest, it is perfectly fine installing the module for it.

The library has no *stable* (you'd surprised how less-nightly it will be :joy: ) because there's none needed yet. The only products requiring the library are Icinga Web 2 and Icinga DB Web. Both versions requiring this have no release yet as well.

--

So if the installation steps for the Director tell you to install the module.. install the module. :smiley:

**Comment by nilmerg** [comment]
Icinga Web 2 Version 2.9.0 is now released and this library also has a stable release now, closing.
